application: seekika
version: 1
runtime: python
api_version: 1

handlers:
- url: /api/.*
  script: api.py
  
  auth_fail_action: unauthorized
  
  
- url: /.*
  script: seekika.py
  
  
  
- url: /static/stylesheets
  static_dir: css
  
- url: /static/images
  static_dir: images